# Generated by Django 4.2.2 on 2023-06-29 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Spend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('amount_spent', models.FloatField()),
                ('date', models.DateField()),
                ('date_of_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
