# Generated by Django 4.2.2 on 2023-06-29 19:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('spends', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spend',
            name='category',
            field=models.CharField(blank=True, choices=[('groceries', 'groceries'), ('transportation', 'transportation'), ('entertainment', 'entertainment')], max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='spend',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_spends', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('slug', models.SlugField(max_length=70)),
                ('spend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='spends.spend')),
            ],
        ),
    ]
