# Generated by Django 4.2.2 on 2023-07-04 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spends', '0002_spend_category_spend_user_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spend',
            name='category',
            field=models.CharField(blank=True, choices=[('groceries', 'продукты'), ('transportation', 'транспорт'), ('entertainment', 'развлечения'), ('housing', 'дом'), ('medical', 'медицина')], max_length=70, null=True),
        ),
    ]
