# Generated by Django 4.2.2 on 2023-07-05 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spends', '0003_alter_spend_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='slug',
        ),
        migrations.AlterField(
            model_name='spend',
            name='category',
            field=models.CharField(blank=True, choices=[('', '--------'), ('groceries', 'продукты'), ('transportation', 'транспорт'), ('entertainment', 'развлечения'), ('housing', 'дом'), ('medical', 'медицина')], max_length=70, null=True),
        ),
    ]
